# Generated by Django 5.1.5 on 2025-01-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='telegram_user_id',
            field=models.CharField(blank=True, help_text='ID пользователя в Telegram', max_length=50, null=True),
        ),
    ]
