# Generated by Django 5.1.5 on 2025-01-27 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_telegram_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['id']},
        ),
    ]
