# Generated by Django 5.1.5 on 2025-01-28 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='telegram_user_id',
        ),
    ]
